<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="demo_motor_simulation">

  <link name="map"></link>

  <xacro:property name="motor_mass" value="100"/>
  <xacro:property name="motor_size" value="0.16"/>
  <xacro:property name="motor_height" value="0.3"/>
  <link name="motor_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${(motor_height/2)}" />
      <geometry>
        <box size="${motor_size} ${motor_size} ${motor_height}" />
      </geometry>
      <material name="Green">
        <color rgba="0.2 1.0 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0 " xyz="0 0 ${(motor_height/2)}" />
      <geometry>
        <box size="${motor_size} ${motor_size} ${motor_height}" />
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0 " xyz="0 0 ${(motor_height/2)}" />
      <geometry>
        <box size="${motor_size} ${motor_size} ${motor_height}" />
      </geometry>
      <mass value="${motor_mass}" />
      <inertia ixx="1.0265" ixy="0" ixz="0" iyy="1.3944999999999999" iyz="0" izz="2.1320000000000001" />
    </inertial>
  </link>

  <joint name="motor_joint" type="fixed">
    <parent link="map"/>
    <child link="motor_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <gazebo reference="motor_link">
    <material>Gazebo/Green</material>
  </gazebo>


  <!-- A wheel -->
  <xacro:property name="wheel_mass" value="3.5"/>
  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_thick" value="0.05"/>
  <link name="wheel_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thick}" radius="${wheel_radius}"/>
      </geometry>
      <material name="Blue">
        <color rgba="0.2 0.2 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thick}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thick}" radius="${wheel_radius}"/>
      </geometry>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.0267" ixy="0" ixz="0" iyy="0.0267" iyz="0" izz="0.0506"/>
    </inertial>
  </link>

  <joint name="wheel_joint" type="continuous">
    <parent link="motor_link"/>
    <child link="wheel_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${motor_height + 0.02}"/>
    <axis xyz="0 0 1" />
  </joint>

  <gazebo reference="wheel_link">
    <material>Gazebo/Blue</material>
  </gazebo>


  <gazebo>
    <!-- Publish the position of the given joints as sensor_msgs/msg/JointState message to the topic /joint_states -->
    <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <update_rate>10</update_rate>
      <joint_name>wheel_joint</joint_name>
    </plugin>

    <!-- Reads a trajectory_msgs/msg/JointTrajectory from /set_joint_trajectory and uses that for a new joint state -->
    <plugin name="gazebo_ros_joint_pose_trajectory" filename="libgazebo_ros_joint_pose_trajectory.so">
      <update_rate>10</update_rate>
    </plugin>
  </gazebo>

</robot>
